services:
  test_db:
    container_name: "test_db"
    image: postgres:16
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --locale=C
    ports:
      - ${TEST_POSTGRES_PORT:-5432}:5432
    volumes:
      - test_db_data:/var/lib/postgresql/data
    restart: always

volumes:
  test_db_data:
