services:
  app:
    container_name: "app"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${APP_PORT:-8000}:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    restart: always

  db:
    container_name: "db"
    image: postgres:16
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data:
