"""empty message

Revision ID: f6dc12caa645
Revises:
Create Date: 2024-07-11 13:20:22.466215

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f6dc12caa645"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_analysis_log",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="ID",
        ),
        sa.Column(
            "image_path",
            sa.String(length=255),
            nullable=True,
            comment="画像ファイルパス",
        ),
        sa.Column(
            "success", sa.Boolean(), nullable=False, comment="リクエスト成功か"
        ),
        sa.Column(
            "message",
            sa.String(length=255),
            nullable=True,
            comment="メッセージ",
        ),
        sa.Column("class_", sa.Integer(), nullable=True, comment="クラス"),
        sa.Column(
            "confidence",
            sa.DECIMAL(precision=5, scale=4),
            nullable=True,
            comment="信頼度",
        ),
        sa.Column(
            "request_timestamp",
            sa.DateTime(),
            nullable=True,
            comment="リクエストタイムスタンプ",
        ),
        sa.Column(
            "response_timestamp",
            sa.DateTime(),
            nullable=True,
            comment="レスポンスタイムスタンプ",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ai_analysis_log")
    # ### end Alembic commands ###
