name: Run tests

run-name: Run tests by ${{ github.actor }}

on: [push, workflow_dispatch]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      test-db:
        image: postgres:16
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: password
          POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=C
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry install --no-root

      - name: Run FastAPI
        run: |
          poetry run fastapi dev api/main.py --host 0.0.0.0 &
          until curl -s http://127.0.0.1:8000; do sleep 1; done

      - name: Run tests
        env:
          TEST_POSTGRES_HOST: 127.0.0.1
          MOCK_UP_DOMAIN: http://127.0.0.1:8000
        run:
          poetry run pytest ./tests
